name: Monthly ETL (SaaS)

on:
  schedule:
    - cron: "15 2 3 * *"   # 03. des Monats, 02:15 UTC
  workflow_dispatch:
    inputs:
      period_year:  { type: string, required: false, description: "YYYY" }
      period_month: { type: string, required: false, description: "M oder MM" }
      tenants:      { type: string, required: false, description: "CSV oder ALL", default: "ALL" }
      which:        { type: choice,  required: false, default: beides, options: [beides, fees, orders] }
      
permissions:
  contents: read
  actions: write

jobs:
  call:
    uses: ./.github/workflows/_saas-etl.yml
    with:
      period_year:  ${{ inputs.period_year }}
      period_month: ${{ inputs.period_month }}
      tenants:      ${{ inputs.tenants || 'ALL' }}
      which:        ${{ inputs.which || 'beides' }}
      max_parallel: 8
    secrets: inherit
