name: Monthly ETL

on:
  schedule:
    - cron: "15 2 3 * *"   # 03. des Monats um 02:15 UTC
  workflow_dispatch: {}

jobs:
  fees:
    runs-on: ubuntu-latest
    env:
      TENANT_ID: ${{ vars.TENANT_ID }}
      SELLER_ID: ${{ vars.SELLER_ID }}
      MARKETPLACES_JSON: ${{ vars.MARKETPLACES_JSON }}
      CODE_DIR: ${{ vars.CODE_DIR }}              # optional override
      FEE_SCRIPT: ${{ vars.FEE_SCRIPT }}          # optional override, default AmzT_Fee.py
      SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
      SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}   # bevorzugt für Fees
      SUPABASE_SERVICE_ROLE_KEY: ${{ secrets.SUPABASE_SERVICE_ROLE_KEY }} # Fallback
      LWA_APP_ID: ${{ secrets.LWA_APP_ID }}
      LWA_CLIENT_ID: ${{ secrets.LWA_CLIENT_ID }} # Fallback-Name
      AMAZON_APP_ID: ${{ secrets.AMAZON_APP_ID }} # Fallback-Name
      LWA_CLIENT_SECRET: ${{ secrets.LWA_CLIENT_SECRET }}
      SP_API_REFRESH_TOKEN: ${{ secrets.SP_API_REFRESH_TOKEN }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with: { python-version: "3.11" }

      - name: Install dependencies
        run: |
          python -m pip install -U pip
          pip install -U python-amazon-sp-api python-dotenv supabase requests tzdata

      - name: Show repo (top)
        run: |
          echo "PWD=$(pwd)"
          find . -maxdepth 4 -type f | sed -n '1,400p'

      - name: Normalize, autodetect CODE_DIR & validate (fees)
        run: |
          set -e
          python - << 'PY'
          import os, json, sys, re, pathlib
          root = pathlib.Path(".").resolve()
          env_file = os.environ["GITHUB_ENV"]
          def exp(k,v):
              with open(env_file,"a") as f: f.write(f"{k}={v}\n")
              print(f"export {k}={v if k in ('CODE_DIR','FEE_SCRIPT','MARKETPLACES_JSON') else '***'}")

          # ---- normalize LWA_APP_ID
          lwa = os.getenv("LWA_APP_ID") or os.getenv("LWA_CLIENT_ID") or os.getenv("AMAZON_APP_ID")
          if not lwa: print("ERROR: need LWA_APP_ID/LWA_CLIENT_ID/AMAZON_APP_ID"); sys.exit(1)
          exp("LWA_APP_ID", lwa)

          # ---- supabase key (fees)
          sb_url = os.getenv("SUPABASE_URL")
          sb_key = os.getenv("SUPABASE_KEY") or os.getenv("SUPABASE_SERVICE_ROLE_KEY")
          if not (sb_url and sb_key): print("ERROR: SUPABASE_URL and one of SUPABASE_KEY/SERVICE_ROLE"); sys.exit(1)
          exp("SUPABASE_KEY", sb_key)

          # ---- tenant
          tenant = (os.getenv("TENANT_ID") or os.getenv("SELLER_ID") or "default").strip()
          exp("TENANT_ID", tenant)

          # ---- marketplaces tolerant
          raw = os.getenv("MARKETPLACES_JSON","")
          if not raw:
              arr = ["DE"]
          else:
              try:
                  val = json.loads(raw)
              except Exception:
                  val = raw
              if isinstance(val, str):
                  s = val.strip().strip('"').strip("'")
                  parts = [p.strip() for p in re.split(r'[,\s]+', s) if p.strip()]
                  arr = [p.upper() for p in parts] or ["DE"]
              elif isinstance(val, list):
                  arr = [str(x).strip().upper() for x in val if str(x).strip()] or ["DE"]
              else:
                  print('ERROR: MARKETPLACES_JSON must be like DE or ["DE","FR"]'); sys.exit(1)
          exp("MARKETPLACES_JSON", json.dumps(arr))

          # ---- required secrets
          for k in ["LWA_CLIENT_SECRET","SP_API_REFRESH_TOKEN","SUPABASE_URL"]:
              if not os.getenv(k): print(f"ERROR: missing {k}") or sys.exit(1)

          # ---- locate fee script
          fee_script = os.getenv("FEE_SCRIPT") or "AmzT_Fee.py"
          code_dir = os.getenv("CODE_DIR")
          candidates = []
          cand_names = [fee_script, "AmzT_Fees.py", "orders_month_fees_supabase_parallel.py"]
          if code_dir:
              base = root / code_dir
              for n in cand_names:
                  p = base / n
                  if p.exists():
                      candidates.append(p)
                      break
          if not candidates:
              for n in cand_names:
                  candidates += list(root.rglob(n))
          if not candidates:
              print("ERROR: Could not locate fee script. Looked for:", cand_names)
              sys.exit(1)
          pick = sorted(candidates, key=lambda p: len(str(p)))[0]
          exp("CODE_DIR", str(pick.parent))
          exp("FEE_SCRIPT", pick.name)
          print("Config (fees) normalized ✓")
          PY

      - name: Run Fees (last month) for each marketplace
        working-directory: ${{ env.CODE_DIR }}
        env:
          LOCAL_TZ: "Europe/Berlin"
        run: |
          set -e
          LM_YEAR=$(date -u -d "$(date -u +%Y-%m-01) -1 month" +%Y)
          LM_MONTH=$(date -u -d "$(date -u +%Y-%m-01) -1 month" +%-m)
          echo "Period: ${LM_YEAR}-${LM_MONTH}"

          MPS=$(python - <<'PY'
          import os, json; print(" ".join(json.loads(os.environ["MARKETPLACES_JSON"])))
          PY
          )

          for MP in $MPS; do
            echo "=== Fees → $MP ==="
            export MARKETPLACE="$MP"
            export ORDERS_YEAR="$LM_YEAR"
            export ORDERS_MONTH="$LM_MONTH"
            python "$FEE_SCRIPT"
          done

  orders:
    runs-on: ubuntu-latest
    needs: fees
    env:
      TENANT_ID: ${{ vars.TENANT_ID }}
      SELLER_ID: ${{ vars.SELLER_ID }}
      MARKETPLACES_JSON: ${{ vars.MARKETPLACES_JSON }}
      CODE_DIR: ${{ vars.CODE_DIR }}                # optional override
      ORDERS_SCRIPT: ${{ vars.ORDERS_SCRIPT }}      # optional override, default AmzT_Sales.py
      SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
      SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}     # Fallback
      SUPABASE_SERVICE_ROLE_KEY: ${{ secrets.SUPABASE_SERVICE_ROLE_KEY }} # bevorzugt für Orders
      LWA_APP_ID: ${{ secrets.LWA_APP_ID }}
      LWA_CLIENT_ID: ${{ secrets.LWA_CLIENT_ID }}
      AMAZON_APP_ID: ${{ secrets.AMAZON_APP_ID }}
      LWA_CLIENT_SECRET: ${{ secrets.LWA_CLIENT_SECRET }}
      SP_API_REFRESH_TOKEN: ${{ secrets.SP_API_REFRESH_TOKEN }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with: { python-version: "3.11" }

      - name: Install dependencies
        run: |
          python -m pip install -U pip
          pip install -U python-amazon-sp-api python-dotenv supabase requests tzdata

      - name: Normalize, autodetect CODE_DIR & validate (orders)
        run: |
          set -e
          python - << 'PY'
          import os, json, sys, re, pathlib
          root = pathlib.Path(".").resolve()
          env_file = os.environ["GITHUB_ENV"]
          def exp(k,v):
              with open(env_file,"a") as f: f.write(f"{k}={v}\n")
              print(f"export {k}={v if k in ('CODE_DIR','ORDERS_SCRIPT','MARKETPLACES_JSON') else '***'}")

          lwa = os.getenv("LWA_APP_ID") or os.getenv("LWA_CLIENT_ID") or os.getenv("AMAZON_APP_ID")
          if not lwa: print("ERROR: need LWA_APP_ID/LWA_CLIENT_ID/AMAZON_APP_ID"); sys.exit(1)
          exp("LWA_APP_ID", lwa)

          # orders → service role bevorzugt
          sb_url = os.getenv("SUPABASE_URL")
          srv = os.getenv("SUPABASE_SERVICE_ROLE_KEY") or os.getenv("SUPABASE_KEY")
          if not (sb_url and srv): print("ERROR: SUPABASE_URL and one of SERVICE_ROLE/KEY required"); sys.exit(1)
          exp("SUPABASE_SERVICE_ROLE_KEY", srv)

          tenant = (os.getenv("TENANT_ID") or os.getenv("SELLER_ID") or "default").strip()
          exp("TENANT_ID", tenant)

          raw = os.getenv("MARKETPLACES_JSON","")
          if not raw:
              arr = ["DE"]
          else:
              try:
                  val = json.loads(raw)
              except Exception:
                  val = raw
              if isinstance(val, str):
                  s = val.strip().strip('"').strip("'")
                  parts = [p.strip() for p in re.split(r'[,\s]+', s) if p.strip()]
                  arr = [p.upper() for p in parts] or ["DE"]
              elif isinstance(val, list):
                  arr = [str(x).strip().upper() for x in val if str(x).strip()] or ["DE"]
              else:
                  print('ERROR: MARKETPLACES_JSON must be like DE or ["DE","FR"]'); sys.exit(1)
          exp("MARKETPLACES_JSON", json.dumps(arr))

          for k in ["LWA_CLIENT_SECRET","SP_API_REFRESH_TOKEN","SUPABASE_URL"]:
              if not os.getenv(k): print(f"ERROR: missing {k}") or sys.exit(1)

          # ---- locate orders script
          orders_script = os.getenv("ORDERS_SCRIPT") or "AmzT_Sales.py"
          code_dir = os.getenv("CODE_DIR")
          candidates = []
          cand_names = [orders_script, "orders_month_supabase.py", "AmzT_Orders.py"]
          if code_dir:
              base = root / code_dir
              for n in cand_names:
                  p = base / n
                  if p.exists():
                      candidates.append(p)
                      break
          if not candidates:
              for n in cand_names:
                  candidates += list(root.rglob(n))
          if not candidates:
              print("ERROR: Could not locate orders script. Looked for:", cand_names)
              sys.exit(1)
          pick = sorted(candidates, key=lambda p: len(str(p)))[0]
          exp("CODE_DIR", str(pick.parent))
          exp("ORDERS_SCRIPT", pick.name)
          print("Config (orders) normalized ✓")
          PY

      - name: Run Orders (last month) for each marketplace
        working-directory: ${{ env.CODE_DIR }}
        env:
          WRITE_CSV: "0"
          ORDERS_DATE_MODE: "created"
        run: |
          set -e
          LM_YEAR=$(date -u -d "$(date -u +%Y-%m-01) -1 month" +%Y)
          LM_MONTH=$(date -u -d "$(date -u +%Y-%m-01) -1 month" +%-m)
          echo "Period: ${LM_YEAR}-${LM_MONTH}"

          MPS=$(python - <<'PY'
          import os, json; print(" ".join(json.loads(os.environ["MARKETPLACES_JSON"])))
          PY
          )

          for MP in $MPS; do
            echo "=== Orders → $MP ==="
            export MARKETPLACE="$MP"
            export ORDERS_YEAR="$LM_YEAR"
            export ORDERS_MONTH="$LM_MONTH"
            python "$ORDERS_SCRIPT"
          done
