name: SaaS ETL (manual run)

on:
  workflow_dispatch:
    inputs:
      period_year:
        description: "YYYY (leer = Vormonat)"
        required: false
        default: ""
      period_month:
        description: "M oder MM (leer = Vormonat)"
        required: false
        default: ""
      tenants:
        description: "CSV von tenant_id(s) oder ALL (z.B. AO5...,ABC...,DEF...)"
        required: true
        default: "ALL"
      which:
        description: "fees | orders | beides"
        required: true
        default: "orders"
      max_parallel:
        description: "1..20"
        required: false
        default: "4"

permissions:
  contents: read
  actions: write

jobs:
  run:
    uses: ./.github/workflows/_saas-etl.yml
    secrets: inherit
    with:
      period_year:   ${{ inputs.period_year }}
      period_month:  ${{ inputs.period_month }}
      tenants:       ${{ inputs.tenants }}
      which:         ${{ inputs.which }}
      max_parallel:  ${{ inputs.max_parallel }}
